id: P000605
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20859
  title: རང་བྱུང་གནོད་འཚེ་སེར་སྐྱོན་སྐོར
  author: ''
  volumes:
    0202e714f38c4921a40ff089dea04f68:
      image_group_id: I1GS105619
      title: ''
      volume_number: 1
      total_pages: 166
